runtime: go
api_version: go1
instance_class: B1
service: backend
basic_scaling:
  max_instances: 8
  idle_timeout: 2m

handlers:
- url: /backend/.*
  script: _go_app
  login: admin

- url: /backend/bksv/.*
  script: _go_app
  login: admin

- url: "/report/summary"
  login: required
#  auth_fail_action: unauthorized
  auth_fail_action: redirect
  script: _go_app

- url: "/report/.*"
  script: _go_app

- url: /_ah/start
  script: _go_app

- url: /_ah/stop
  script: _go_app
