application: serfr0-1000
version: 1
runtime: go
api_version: go1
instance_class: F1

inbound_services:
- mail_bounce

handlers:
- url: /fdb/scan
  script: _go_app
  login: admin
- url: /fdb/addflight
  script: _go_app
  login: admin

- url: /task/.*
  script: _go_app
  login: admin
- url: /cdb/.*
  script: _go_app
  login: admin
- url: /bksv/.*
  script: _go_app
  login: admin

- url: /stats-reset
  script: _go_app
  login: admin
- url: /month
  script: _go_app
  login: admin

- url: /email
  script: _go_app
  login: admin
- url: /emails-for-yesterday
  script: _go_app
  login: admin
- url: /masq
  script: _go_app
  login: admin
- url: /_ah/bounce
  script: _go_app
  login: admin
- url: /static
  static_dir: static
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /apple-touch-icon.png
  static_files: static/icon.png
  upload: static/icon.png
- url: /apple-touch-icon-precomposed.png
  static_files: static/icon.png
  upload: static/icon.png
- url: /apple-touch-icon-120x120.png
  static_files: static/icon.png
  upload: static/icon.png
- url: /apple-touch-icon-120x120-precomposed.png
  static_files: static/icon.png
  upload: static/icon.png
- url: /apple-touch-icon-152x152.png
  static_files: static/icon.png
  upload: static/icon.png
- url: /apple-touch-icon-152x152-precomposed.png
  static_files: static/icon.png
  upload: static/icon.png
- url: /apple-touch-icon-76x76.png
  static_files: static/icon.png
  upload: static/icon.png
- url: /apple-touch-icon-76x76-precomposed.png
  static_files: static/icon.png
  upload: static/icon.png
- url: /.*
  script: _go_app
